import '../models/enums.dart';
import '../models/provider_profile.dart';
import '../models/review.dart';

/// Static demonstration data used to power provider matching, testimonials
/// and marketplace overview screens. Explicitly labeled as demo/sample data
/// in the UI wherever it is displayed, per platform trust requirements.
class DemoDataService {
  DemoDataService._();

  static final List<ProviderProfile> drivers = [
    ProviderProfile(
      id: 'drv_001',
      fullName: 'Marc-Antoine Tremblay',
      profilePhotoUrl: 'https://i.pravatar.cc/150?img=12',
      city: 'Montréal, QC',
      serviceRadiusKm: 25,
      type: UserRole.driver,
      verification: VerificationStatus.verified,
      rating: 4.9,
      completedJobs: 132,
      responseRateHrs: 1,
      languages: ['Français', 'English'],
      memberSince: DateTime(2023, 3, 12),
      identityVerified: true,
      documentsVerified: true,
      vehicleVerified: true,
      vehicleType: VehicleCategory.pickupTruck,
      vehicleMakeModel: 'Ford F-150',
      vehicleYear: 2021,
      maxPayloadKg: 900,
      acceptedItemCategories: ['Meubles', 'Appareils électroménagers', 'Matériaux'],
      hourlyRate: 45,
      perKmRate: 1.2,
      travelFee: 15,
      minimumFee: 60,
    ),
    ProviderProfile(
      id: 'drv_002',
      fullName: 'Sophie Bouchard',
      profilePhotoUrl: 'https://i.pravatar.cc/150?img=47',
      city: 'Laval, QC',
      serviceRadiusKm: 40,
      type: UserRole.driver,
      verification: VerificationStatus.verified,
      rating: 4.8,
      completedJobs: 89,
      responseRateHrs: 2,
      languages: ['Français'],
      memberSince: DateTime(2023, 7, 2),
      identityVerified: true,
      documentsVerified: true,
      vehicleVerified: true,
      vehicleType: VehicleCategory.cargoVan,
      vehicleMakeModel: 'Mercedes Sprinter',
      vehicleYear: 2020,
      maxPayloadKg: 1400,
      acceptedItemCategories: ['Petits déménagements', 'Boîtes', 'Électroménagers'],
      hourlyRate: 55,
      perKmRate: 1.4,
      travelFee: 20,
      minimumFee: 75,
    ),
    ProviderProfile(
      id: 'drv_003',
      fullName: 'Jean-Félix Roy',
      profilePhotoUrl: 'https://i.pravatar.cc/150?img=33',
      city: 'Terrebonne, QC',
      serviceRadiusKm: 30,
      type: UserRole.driver,
      verification: VerificationStatus.verified,
      rating: 4.7,
      completedJobs: 54,
      responseRateHrs: 3,
      languages: ['Français', 'English'],
      memberSince: DateTime(2024, 1, 20),
      identityVerified: true,
      documentsVerified: true,
      vehicleVerified: false,
      vehicleType: VehicleCategory.trailer,
      vehicleMakeModel: 'RAM 1500 + remorque',
      vehicleYear: 2019,
      maxPayloadKg: 1800,
      acceptedItemCategories: ['Motos', 'VTT', 'Palettes', 'Équipement'],
      hourlyRate: 50,
      perKmRate: 1.3,
      travelFee: 18,
      minimumFee: 65,
    ),
  ];

  static final List<ProviderProfile> mechanics = [
    ProviderProfile(
      id: 'mec_001',
      fullName: 'David Gagnon',
      businessName: 'Gagnon Mécanique Mobile',
      profilePhotoUrl: 'https://i.pravatar.cc/150?img=56',
      city: 'Montréal, QC',
      serviceRadiusKm: 20,
      type: UserRole.mechanic,
      verification: VerificationStatus.verified,
      rating: 4.9,
      completedJobs: 210,
      responseRateHrs: 1,
      languages: ['Français', 'English'],
      memberSince: DateTime(2022, 9, 5),
      identityVerified: true,
      documentsVerified: true,
      specialties: ['Freins', 'Batterie', 'Diagnostic', "Démarrage d'urgence"],
      yearsExperience: 12,
      emergencyAvailable: true,
      hourlyRate: 85,
      perKmRate: 0,
      travelFee: 25,
      minimumFee: 90,
    ),
    ProviderProfile(
      id: 'mec_002',
      fullName: 'Isabelle Cormier',
      businessName: 'Mécanique Mobile Cormier',
      profilePhotoUrl: 'https://i.pravatar.cc/150?img=45',
      city: 'Longueuil, QC',
      serviceRadiusKm: 30,
      type: UserRole.mechanic,
      verification: VerificationStatus.verified,
      rating: 4.8,
      completedJobs: 156,
      responseRateHrs: 2,
      languages: ['Français'],
      memberSince: DateTime(2023, 2, 14),
      identityVerified: true,
      documentsVerified: true,
      specialties: ['Changement d\'huile', 'Pneus', 'Suspension', 'Inspection pré-achat'],
      yearsExperience: 8,
      emergencyAvailable: false,
      hourlyRate: 75,
      perKmRate: 0,
      travelFee: 20,
      minimumFee: 80,
    ),
    ProviderProfile(
      id: 'mec_003',
      fullName: 'Karim Haddad',
      profilePhotoUrl: 'https://i.pravatar.cc/150?img=15',
      city: 'Laval, QC',
      serviceRadiusKm: 35,
      type: UserRole.mechanic,
      verification: VerificationStatus.verified,
      rating: 4.6,
      completedJobs: 72,
      responseRateHrs: 4,
      languages: ['Français', 'English', 'Español'],
      memberSince: DateTime(2023, 11, 30),
      identityVerified: true,
      documentsVerified: false,
      specialties: ['Alternateur', 'Démarreur', 'Diagnostic OBD'],
      yearsExperience: 6,
      emergencyAvailable: true,
      hourlyRate: 70,
      perKmRate: 0,
      travelFee: 22,
      minimumFee: 75,
    ),
  ];

  static List<ProviderProfile> get allProviders => [...drivers, ...mechanics];

  /// Canonical, locale-independent keys for item categories. These are the
  /// values stored on requests (`itemCategory`) and provider profiles; use
  /// `LocaleProvider.t(key)` / `AppStrings.t(key, locale)` to render the
  /// translated label for the active locale.
  static const deliveryCategories = [
    'cat_furniture',
    'cat_appliances',
    'cat_marketplace',
    'cat_costco',
    'cat_home_depot',
    'cat_building_materials',
    'cat_pallets',
    'cat_equipment',
    'cat_bbq',
    'cat_tv',
    'cat_boxes',
    'cat_motorcycle',
    'cat_atv',
    'cat_small_move',
  ];

  /// Canonical, locale-independent keys for mechanic services. Stored on
  /// requests (`selectedServices`) and provider profiles; translate for
  /// display via `LocaleProvider.t(key)` / `AppStrings.t(key, locale)`.
  static const mechanicServices = [
    'svc_battery_boost',
    'svc_battery_replacement',
    'svc_oil_change',
    'svc_brakes',
    'svc_tires',
    'svc_suspension',
    'svc_starter',
    'svc_alternator',
    'svc_obd_diagnostic',
    'svc_warning_light',
    'svc_wont_start',
    'svc_noise_vibration',
    'svc_pre_purchase_inspection',
    'svc_roadside_emergency',
    'svc_other',
  ];

  static final List<Review> testimonials = [
    Review(
      id: 'test_001',
      bookingId: 'demo',
      authorName: 'Client Movi-k',
      targetProviderId: 'drv_001',
      overall: 5.0,
      categoryRatings: const {'Ponctualité': 5, 'Communication': 5, 'Soin des objets': 5},
      comment: 'Livraison rapide et chauffeur très professionnel, mon divan est arrivé sans aucun dommage.',
      createdAt: DateTime(2024, 5, 2),
    ),
    Review(
      id: 'test_002',
      bookingId: 'demo',
      authorName: 'Client Movi-k',
      targetProviderId: 'mec_001',
      overall: 4.8,
      categoryRatings: const {'Ponctualité': 5, 'Qualité du travail': 5, 'Transparence des prix': 4.5},
      comment: 'Le mécanicien est venu directement à mon travail pour changer ma batterie. Service impeccable.',
      createdAt: DateTime(2024, 6, 18),
    ),
    Review(
      id: 'test_003',
      bookingId: 'demo',
      authorName: 'Client Movi-k',
      targetProviderId: 'drv_002',
      overall: 4.9,
      categoryRatings: const {'Ponctualité': 5, 'Communication': 4.8, 'Professionnalisme': 5},
      comment: 'Super expérience pour transporter mes électroménagers achetés chez Home Depot.',
      createdAt: DateTime(2024, 7, 9),
    ),
  ];
}
